name: Build update-nixos-release
"on":
  pull_request:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/build-update-nixos-release.yaml
      - flake.lock
      - packages/update-nixos-release/**
  push:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/build-update-nixos-release.yaml
      - flake.lock
      - packages/update-nixos-release/**
  workflow_dispatch:

jobs:
  build-update-nixos-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Build update-nixos-release
        run: nix build '.#update-nixos-release'
