name: Build update-nix-direnv
"on":
  pull_request:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/build-update-nix-direnv.yaml
      - flake.lock
      - packages/update-nix-direnv/**
  push:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/build-update-nix-direnv.yaml
      - flake.lock
      - packages/update-nix-direnv/**
  workflow_dispatch:

jobs:
  build-update-nix-direnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/magic-nix-cache-action@v10
      - name: Build update-nix-direnv
        run: nix build '.#update-nix-direnv'
