name: Build update-nixos-release
"on":
  pull_request:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/build-update-nixos-release.yaml
      - flake.lock
      - update-nixos-release.nu
      - update-nixos-release-tests.nu
  push:
    branches: ["main"]
    paths:
      - '**.nix'
      - .github/workflows/build-update-nixos-release.yaml
      - flake.lock
      - update-nixos-release.nu
      - update-nixos-release-tests.nu
  workflow_dispatch:

jobs:
  build-update-nixos-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build update-nixos-release
        run: nix build '.#update-nixos-release'
